-- Insert 50 books into the 'books' table
INSERT INTO book (title, author, number_of_pages) VALUES
                                                     ('To Kill a Mockingbird', 'Harper Lee', 281),
                                                     ('1984', 'George Orwell', 328),
                                                     ('The Great Gatsby', 'F. Scott Fitzgerald', 180),
                                                     ('One Hundred Years of Solitude', 'Gabriel García Márquez', 417),
                                                     ('Moby Dick', 'Herman Melville', 635),
                                                     ('War and Peace', 'Leo Tolstoy', 1225),
                                                     ('Crime and Punishment', 'Fyodor Dostoevsky', 671),
                                                     ('The Catcher in the Rye', 'J.D. Salinger', 277),
                                                     ('Pride and Prejudice', 'Jane Austen', 432),
                                                     ('The Hobbit', 'J.R.R. Tolkien', 310),
                                                     ('Ulysses', 'James Joyce', 730),
                                                     ('Brave New World', 'Aldous Huxley', 311),
                                                     ('The Brothers Karamazov', 'Fyodor Dostoevsky', 796),
                                                     ('Anna Karenina', 'Leo Tolstoy', 864),
                                                     ('Madame Bovary', 'Gustave Flaubert', 329),
                                                     ('The Picture of Dorian Gray', 'Oscar Wilde', 254),
                                                     ('Frankenstein', 'Mary Shelley', 280),
                                                     ('Don Quixote', 'Miguel de Cervantes', 1072),
                                                     ('Jane Eyre', 'Charlotte Brontë', 500),
                                                     ('The Divine Comedy', 'Dante Alighieri', 798),
                                                     ('The Stranger', 'Albert Camus', 123),
                                                     ('The Count of Monte Cristo', 'Alexandre Dumas', 1276),
                                                     ('Wuthering Heights', 'Emily Brontë', 416),
                                                     ('Les Misérables', 'Victor Hugo', 1488),
                                                     ('Dracula', 'Bram Stoker', 418),
                                                     ('The Odyssey', 'Homer', 374),
                                                     ('The Iliad', 'Homer', 704),
                                                     ('The Metamorphosis', 'Franz Kafka', 201),
                                                     ('The Sound and the Fury', 'William Faulkner', 326),
                                                     ('Great Expectations', 'Charles Dickens', 505),
                                                     ('David Copperfield', 'Charles Dickens', 882),
                                                     ('The Scarlet Letter', 'Nathaniel Hawthorne', 272),
                                                     ('Sense and Sensibility', 'Jane Austen', 409),
                                                     ('The Sun Also Rises', 'Ernest Hemingway', 251),
                                                     ('Lolita', 'Vladimir Nabokov', 336),
                                                     ('The Grapes of Wrath', 'John Steinbeck', 464),
                                                     ('The Old Man and the Sea', 'Ernest Hemingway', 127),
                                                     ('Catch-22', 'Joseph Heller', 453),
                                                     ('Beloved', 'Toni Morrison', 324),
                                                     ('Gone with the Wind', 'Margaret Mitchell', 1037),
                                                     ('The Road', 'Cormac McCarthy', 287),
                                                     ('A Tale of Two Cities', 'Charles Dickens', 544),
                                                     ('Fahrenheit 451', 'Ray Bradbury', 158),
                                                     ('Slaughterhouse-Five', 'Kurt Vonnegut', 275),
                                                     ('The Kite Runner', 'Khaled Hosseini', 372),
                                                     ('The Lord of the Rings', 'J.R.R. Tolkien', 1178),
                                                     ('The Shining', 'Stephen King', 447),
                                                     ('It', 'Stephen King', 1138),
                                                     ('Dune', 'Frank Herbert', 604),
                                                     ('The Handmaid Tale', 'Margaret Atwood', 311);
INSERT INTO ready_users (username, password, email, creation_date, active)
VALUES
    ('john_doe', 'pass123', 'john.doe@email.com', '2024-01-01', true),
    ('jane_smith', 'pass123', 'jane.smith@email.com', '2024-02-15', true),
    ('bob_wilson', 'pass123', 'bob.wilson@email.com', '2024-03-20', true),
    ('alice_brown', 'pass123', 'alice.brown@email.com', '2024-04-01', false),
    ('sam_jones', 'pass123', 'sam.jones@email.com', '2024-04-15', true);
